[root]
slack_webhook_url = "https://hooks.slack.com/..."

[nut]
  shutdown_threshold = 20  # Shutdown clients when battery below 20%
  startup_threshold = 50   # Start clients when battery above 50%
  bootstrap_retry_interval = "PT5M"  # Retry bootstrap every 5 minutes on failure

[[nut.managed_hardware]]
  name = "NAS"
  local_ip = "192.168.1.172"
  username = "root"

[[nut.managed_hardware]]
  name = "Dream Machine"
  local_ip = "192.168.1.1"
  username = "root"

[[endpoints.nas]]
  nickname = "unifi-nas"
  ip_address = "192.168.1.172"
  username = "root"
  password = "password"

[[endpoints.b2]]
  nickname = "b2-us
  key_id = ""
  application_key = ""

[[backups.sync]]
  src = "nas:unifi-nas://Common_Drive"
  dst = "b2-eu:bungalo-nas-eu://common_drive"

[iphoto]
  username = "your_username"
  password = "your_password"
  output_directory = "iphoto"
