name: Test

jobs:
  lint:
    name: Python Lint & Type Check
    runs-on: ubuntu-latest
    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "uv"

      - name: Install dependencies
        run: |
          uv pip install ruff pyright

      - name: Run linting and type checking
        run: make lint CHECK_ONLY=true 