name: Test
on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]

jobs:
  lint:
    name: Python Lint & Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Run linting and type checking
        run: make lint CHECK_ONLY=true 